apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-app
  name: busybox-app
spec:
  containers:
  - image: busybox-app:v1.0.0
    name: busybox-app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
